package xyz.pokkst.pokket.util

class Constants {
    companion object {
        val ACTION_SETTINGS_HIDE_BAR = "ACTION_SETTINGS_HIDE_BAR"
        val ACTION_SETTINGS_SHOW_BAR = "ACTION_SETTINGS_SHOW_BAR"
        val ACTION_MAIN_ENABLE_PAGER = "ACTION_MAIN_DISABLE_PAGER"
        val ACTION_FRAGMENT_SEND_SEND = "ACTION_FRAGMENT_SEND_SEND"
        val ACTION_UPDATE_REFRESH = "ACTION_UPDATE_REFRESH"


        val REQUEST_CODE_SCAN_QR = 100


        var QR_SCAN_RESULT = "SCAN_RESULT"
    }
}